### ISSUE TITLE
Cannot run users_by_followers.py "ImportError: cannot import name User"

### ISSUE THREAD

**Issue by tayfunyasar** [instagrambot/instapro#2]
As it shows, there's a problem about running default script.

I searched about "ImportError: cannot import name User" but i think its about sys.path.append method. I've tried something but somehow it didnt worked.

> MacBook-MacBook-Pro:instapro tayfunyasar$  pip install -r requirements.txt
> Requirement already satisfied: requests==2.17.3 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 1))
> Requirement already satisfied: tqdm==4.14.0 in /Library/Python/2.7/site-packages (from -r requirements.txt (line 2))
> Requirement already satisfied: urllib3<1.22,>=1.21.1 in /Library/Python/2.7/site-packages (from requests==2.17.3->-r requirements.txt (line 1))
> Requirement already satisfied: idna<2.6,>=2.5 in /Library/Python/2.7/site-packages (from requests==2.17.3->-r requirements.txt (line 1))
> Requirement already satisfied: certifi>=2017.4.17 in /Library/Python/2.7/site-packages (from requests==2.17.3->-r requirements.txt (line 1))
> Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Library/Python/2.7/site-packages (from requests==2.17.3->-r requirements.txt (line 1))
> MacBook-MacBook-Pro:instapro tayfunyasar$ cd examples/scrapers/
> MacBook-MacBook-Pro:scrapers tayfunyasar$ python 
> config.py              scraper.py             users_by_followers.py  users_by_geotag.py     users_by_hashtag.py
> MacBook-MacBook-Pro:scrapers tayfunyasar$ python users_by_followers.py 
> Traceback (most recent call last):
>   File "users_by_followers.py", line 6, in <module>
>     from instabot import User, Getter
> ImportError: cannot import name User
> MacBook-MacBook-Pro:scrapers tayfunyasar$

**Comment by ohld** [comment]
Thats because you have another instabot installed. That's our bug because we call the different libraries the same name.

To fix that issue you should 
```
pip uninstall instabot
```

**Comment by tayfunyasar** [comment]
now it says about pandas?

> MacBook-MacBook-Pro:scrapers tayfunyasar$ python users_by_followers.py 
> Traceback (most recent call last):
>   File "users_by_followers.py", line 9, in <module>
>     import scraper
>   File "/Users/tayfunyasar/dev/github/instapro/examples/scrapers/scraper.py", line 12, in <module>
>     import pandas as pd
> ImportError: No module named pandas
> MacBook-MacBook-Pro:scrapers tayfunyasar$ 
>

**Comment by ohld** [comment]
just `pip install pandas`

**Comment by tayfunyasar** [comment]
Thanks.

I felt noob enough to deal with Python^^
