### ISSUE TITLE
Does or will this lib support insta messaging?

### ISSUE THREAD

**Issue by Davincible** [instagrambot/instapro#8]
Had a look at the examples and it didn't seem to be in there. So any future plans for supporting insta messaging? 

I found php and js libs that support that feature, but as of now I'm only a python dev so would be nice to have a python implementation.

**Comment by ohld** [comment]
Hi, Instabot supports this methods, but instant library is not under development now. So if you transfer the working code from instabot to instapro, that would be nice.
