### ISSUE TITLE
What is the advantage of using instapro over instabot? 

### ISSUE THREAD

**Issue by JessieMB** [instagrambot/instapro#9]
Hi, great job on these amazing tools! What is the difference between instapro and instabot? I realize that instapro is for developers -- is the difference just more modularity so that programmers can better produce customized scripts?

Thank you for all your hard work!!

**Comment by ohld** [comment]
The killer-feature of instapro is that it can do read-only Instagram requests (e.g. get medias by hashtag) in parallel. So you add as many account as you have and minimize the number of requests for each account to prevent being banned.
